### ISSUE TITLE
Not loading Google API key with prebuilt docker container (selfhosting)

### ISSUE THREAD

**Issue by landrevj** [benlikescode/geohub#119]
Hey! Was looking for something like this project to play with friends and ran into this issue whilst trying to get it set up.

>tl;dr I think the value of `NEXT_PUBLIC_GOOGLE_API_KEY` is baked into the docker image when it is built and doesn't respect the `.env` provided in the compose file until you go into the container and re-run `yarn build`, then restart the container.

Since I use Portainer I needed to modify the provided `docker-compose.yaml` slightly:
```yaml
services:
  geohub:
    container_name: geohub
    image: ghcr.io/benlikescode/geohub:main
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@geohub-mongo:27017
    volumes:
      - /mnt/user/appdata/portainer/compose/37/stack.env:/usr/src/app/.env
    ports:
      - 3000:3000
  mongo:
    container_name: geohub-mongo
    image: mongo
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /mnt/user/appdata/geohub/db:/data/db
```
The contents of `stack.env` being this but with real values:
```ini
MONGO_INITDB_ROOT_USERNAME=...
MONGO_INITDB_ROOT_PASSWORD=...
DB_NAME=geohub
NEXTAUTH_SECRET=...
CRYPTR_SECRET=...
NEXTAUTH_URL=https://...
NEXT_PUBLIC_GOOGLE_API_KEY=...
```

This would boot fine but the map embeds show "Development only" warnings and you get a `NoApiKeys` warning from the google scripts in the console. If you check in the page's `head` you can see this script tag is missing the api key:
```diff
+<script id="__googleMapsScriptId" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?callback=__googleMapsCallback&amp;key=apikeyshouldbehere" defer="" async=""></script>
-<script id="__googleMapsScriptId" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?callback=__googleMapsCallback" defer="" async=""></script>
```

If you check the [Next docs](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser) they state that `NEXT_PUBLIC_` variables are substituted with the appropriate value within the code at build time and therefore won't pick up changes after the fact. To get around this you would need to somehow have the frontend fetch the value dynamically. (Either having an endpoint that provides runtime environment variables, or maybe you could get it from `getServerSideProps` or something. Using the app router may also help but I haven't done much with that yet.) 

To anyone else that runs into this the quick fix is to just get a shell into the container, `cd /usr/src/app`, `yarn build`, then restart the container.
